from typing import Any, Protocol
from uuid import UUID

from capataz_api.domain.entities import ActionDefinition, Execution, Principal, Service


class IdentityProvider(Protocol):
    async def authenticate(
        self, authorization: str | None, headers: dict[str, str]
    ) -> Principal: ...


class ServiceRepository(Protocol):
    async def get_service(self, service_id: str) -> Service | None: ...
    async def list_services(self, **filters: object) -> tuple[list[Service], int]: ...
    async def upsert_service(
        self, service: Service, *, enforce_version: bool = False
    ) -> Service: ...
    async def delete_service(self, service_id: str) -> bool: ...
    async def update_status_cache(self, service_id: str, status: str) -> None: ...
    async def list_actions(self, service_id: str) -> list[ActionDefinition]: ...
    async def list_actions_for_services(
        self, service_ids: list[str]
    ) -> dict[str, list[ActionDefinition]]: ...
    async def get_action(self, service_id: str, key: str) -> ActionDefinition | None: ...
    async def upsert_action(self, action: ActionDefinition) -> ActionDefinition: ...
    async def delete_action(self, service_id: str, key: str) -> bool: ...
    async def create_execution(self, execution: Execution) -> Execution: ...
    async def get_execution(self, execution_id: UUID) -> Execution | None: ...
    async def list_executions(self, **filters: object) -> tuple[list[Execution], int]: ...
    async def events(self, execution_id: UUID) -> list[dict[str, Any]]: ...
    async def append_audit(self, event: dict[str, Any]) -> None: ...
    async def list_audit(self, **filters: object) -> tuple[list[dict[str, Any]], int]: ...


class ExecutionQueue(Protocol):
    async def enqueue(self, execution_id: UUID) -> str: ...


class StatusCache(Protocol):
    async def get(self, service_id: str) -> dict[str, Any] | None: ...
    async def set(self, service_id: str, value: dict[str, Any], ttl: int) -> None: ...


class ContainerPlatformPort(Protocol):
    async def container_states(
        self, environment_id: str, selectors: dict[str, Any]
    ) -> list[dict[str, Any]]: ...


class HealthProbePort(Protocol):
    async def probe(self, config: dict[str, Any]) -> bool: ...
