from collections.abc import Mapping
from typing import Any, Protocol
from uuid import UUID

from capataz_api.domain.entities import (
    ActionDefinition,
    Connector,
    Execution,
    Principal,
    Resource,
    Service,
)
from capataz_api.domain.specs import ResourceSource


class IdentityProvider(Protocol):
    async def authenticate(
        self, authorization: str | None, headers: dict[str, str]
    ) -> Principal: ...


class ServiceRepository(Protocol):
    async def get_service(self, service_id: str) -> Service | None: ...
    async def list_services(self, **filters: object) -> tuple[list[Service], int]: ...
    async def upsert_service(
        self, service: Service, *, enforce_version: bool = False
    ) -> Service: ...
    async def delete_service(self, service_id: str) -> bool: ...
    async def update_status_cache(self, service_id: str, status: str) -> None: ...
    async def list_actions(self, service_id: str) -> list[ActionDefinition]: ...
    async def list_actions_for_services(
        self, service_ids: list[str]
    ) -> dict[str, list[ActionDefinition]]: ...
    async def get_action(self, service_id: str, key: str) -> ActionDefinition | None: ...
    async def list_actions_by_connector(self, connector_id: str) -> list[ActionDefinition]: ...
    async def upsert_action(self, action: ActionDefinition) -> ActionDefinition: ...
    async def delete_action(self, service_id: str, key: str) -> bool: ...
    async def create_execution(self, execution: Execution) -> Execution: ...
    async def get_execution(self, execution_id: UUID) -> Execution | None: ...
    async def list_executions(self, **filters: object) -> tuple[list[Execution], int]: ...
    async def events(self, execution_id: UUID) -> list[dict[str, Any]]: ...
    async def append_audit(self, event: dict[str, Any]) -> None: ...
    async def list_audit(self, **filters: object) -> tuple[list[dict[str, Any]], int]: ...
    async def get_resource(self, resource_id: str) -> Resource | None: ...
    async def list_resources(self) -> list[Resource]: ...
    async def upsert_resource(self, resource: Resource) -> Resource: ...
    async def delete_resource(self, resource_id: str) -> bool: ...
    async def get_connector(self, connector_id: str) -> Connector | None: ...
    async def list_connectors(self) -> list[Connector]: ...
    async def upsert_connector(
        self, connector: Connector, *, enforce_version: bool = False
    ) -> Connector: ...
    async def delete_connector(self, connector_id: str) -> bool: ...


class ExecutionQueue(Protocol):
    async def enqueue(self, execution_id: UUID) -> str: ...


class ContainerPlatformPort(Protocol):
    async def container_states(
        self, environment_id: str, selectors: dict[str, Any]
    ) -> list[dict[str, Any]]: ...
    async def find_link_target(
        self, environment_id: str, selectors: dict[str, Any]
    ) -> str | None: ...


class HealthProbePort(Protocol):
    async def probe(self, config: dict[str, Any]) -> bool: ...


class MetricsProviderPort(Protocol):
    async def query(self, definitions: list[dict[str, Any]]) -> list[dict[str, Any]]: ...


class ResourceCipher(Protocol):
    def encrypt(self, plaintext: bytes) -> bytes: ...
    def decrypt(self, ciphertext: bytes) -> bytes: ...
    def fingerprint(self, plaintext: bytes) -> str: ...


class ResourceSourceLoader(Protocol):
    """Reads a catalog resource's plaintext from its declared source (file/env/inline).

    Raises domain ValidationError with a safe message; never includes the content in it.
    """

    def load(self, source: ResourceSource) -> bytes: ...


class ConnectorClientFactory(Protocol):
    """Builds outbound clients for a connector; `secrets` maps config field -> plaintext."""

    def platform(
        self, connector: Connector, secrets: Mapping[str, str]
    ) -> ContainerPlatformPort: ...
    def metrics(self, connector: Connector, secrets: Mapping[str, str]) -> MetricsProviderPort: ...
    def prober(self, connector: Connector) -> HealthProbePort: ...
