/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_v1_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_v1_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_api_v1_services__service_id__get"];
        put?: never;
        post?: never;
        /** Delete Service */
        delete: operations["delete_service_api_v1_services__service_id__delete"];
        options?: never;
        head?: never;
        /** Patch Service */
        patch: operations["patch_service_api_v1_services__service_id__patch"];
        trace?: never;
    };
    "/api/v1/services/{service_id}/refresh-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Status */
        post: operations["refresh_status_api_v1_services__service_id__refresh_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_services__service_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Links */
        get: operations["links_api_v1_services__service_id__links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actions */
        get: operations["list_actions_api_v1_services__service_id__actions_get"];
        put?: never;
        /** Create Action */
        post: operations["create_action_api_v1_services__service_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}/actions/{action_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Action */
        delete: operations["delete_action_api_v1_services__service_id__actions__action_key__delete"];
        options?: never;
        head?: never;
        /** Patch Action */
        patch: operations["patch_action_api_v1_services__service_id__actions__action_key__patch"];
        trace?: never;
    };
    "/api/v1/services/{service_id}/actions/{action_key}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute */
        post: operations["execute_api_v1_services__service_id__actions__action_key__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Executions */
        get: operations["list_executions_api_v1_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution_api_v1_executions__execution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{execution_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_executions__execution_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{execution_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Execution */
        post: operations["cancel_execution_api_v1_executions__execution_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Catalog Import */
        post: operations["catalog_import_api_v1_catalog_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Export */
        get: operations["catalog_export_api_v1_catalog_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_api_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionInput */
        ActionInput: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            action_type: components["schemas"]["ActionType"];
            risk_level: components["schemas"]["RiskLevel"];
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /**
             * Requires Confirmation
             * @default false
             */
            requires_confirmation: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Unattended
             * @default false
             */
            unattended: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Allowed Parameters Schema */
            allowed_parameters_schema?: {
                [key: string]: unknown;
            };
        };
        /** ActionResponse */
        ActionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Service Id */
            service_id: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            action_type: components["schemas"]["ActionType"];
            risk_level: components["schemas"]["RiskLevel"];
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Requires Confirmation */
            requires_confirmation: boolean;
            /** Enabled */
            enabled: boolean;
            /** Unattended */
            unattended: boolean;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Allowed Parameters Schema */
            allowed_parameters_schema: {
                [key: string]: unknown;
            };
        };
        /**
         * ActionType
         * @enum {string}
         */
        ActionType: "portainer" | "ansible" | "http" | "ssh" | "rsync";
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Id */
            id: string;
            /** Timestamp */
            timestamp: string;
            /** Actor */
            actor: string;
            /** Actor Name */
            actor_name?: string | null;
            /** Actor Email */
            actor_email?: string | null;
            /** Action */
            action: string;
            /** Resource */
            resource: string;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id?: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** CatalogFieldErrorResponse */
        CatalogFieldErrorResponse: {
            /** Path */
            path: string;
            /** Message */
            message: string;
            /** Line */
            line?: number | null;
        };
        /** CatalogImport */
        CatalogImport: {
            /** Yaml */
            yaml: string;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** CatalogImportResponse */
        CatalogImportResponse: {
            /** Dry Run */
            dry_run: boolean;
            /** Valid */
            valid: boolean;
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /** Errors */
            errors?: components["schemas"]["CatalogFieldErrorResponse"][];
        };
        /** ExecuteInput */
        ExecuteInput: {
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** @default ui */
            source: components["schemas"]["ExecutionSource"];
            /**
             * Confirmation
             * @default false
             */
            confirmation: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ExecutionEventResponse */
        ExecutionEventResponse: {
            /** Id */
            id: string;
            /** Sequence */
            sequence: number;
            /** Timestamp */
            timestamp: string;
            /** Level */
            level: string;
            /** Event Type */
            event_type: string;
            /** Message */
            message: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** ExecutionResponse */
        ExecutionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Service Id */
            service_id: string | null;
            /** Service Id Snapshot */
            service_id_snapshot: string;
            /** Action Definition Id */
            action_definition_id: string | null;
            /** Action Key */
            action_key: string;
            /** Requested By Subject */
            requested_by_subject: string;
            /** Requested By Email */
            requested_by_email?: string | null;
            /** Requested By Name */
            requested_by_name?: string | null;
            source: components["schemas"]["ExecutionSource"];
            /** Params */
            params: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ExecutionStatus"];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Correlation Id */
            correlation_id: string;
            /** Worker Task Id */
            worker_task_id?: string | null;
            /** Result Summary */
            result_summary?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Summary */
            error_summary?: string | null;
        };
        /**
         * ExecutionSource
         * @enum {string}
         */
        ExecutionSource: "ui" | "api" | "yaml" | "n8n" | "mcp" | "cron" | "alert" | "system";
        /**
         * ExecutionStatus
         * @enum {string}
         */
        ExecutionStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "timed_out" | "rejected";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page[AuditEventResponse] */
        Page_AuditEventResponse_: {
            /** Items */
            items: components["schemas"]["AuditEventResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[ExecutionResponse] */
        Page_ExecutionResponse_: {
            /** Items */
            items: components["schemas"]["ExecutionResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[ServiceResponse] */
        Page_ServiceResponse_: {
            /** Items */
            items: components["schemas"]["ServiceResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "read" | "operate" | "critical";
        /** ServiceInput */
        ServiceInput: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Group Name */
            group_name: string;
            /** Environment */
            environment: string;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Service Url */
            service_url?: string | null;
            /** Documentation Url */
            documentation_url?: string | null;
            /** Portainer Environment Id */
            portainer_environment_id?: string | null;
            /** Portainer Stack Name */
            portainer_stack_name?: string | null;
            /** Container Selectors */
            container_selectors?: {
                [key: string]: unknown;
            };
            /** Health Config */
            health_config?: {
                [key: string]: unknown;
            };
            /** Grafana Config */
            grafana_config?: {
                [key: string]: unknown;
            };
            /** Loki Config */
            loki_config?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Maintenance
             * @default false
             */
            maintenance: boolean;
        };
        /** ServicePatch */
        ServicePatch: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Group Name */
            group_name: string;
            /** Environment */
            environment: string;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Service Url */
            service_url?: string | null;
            /** Documentation Url */
            documentation_url?: string | null;
            /** Portainer Environment Id */
            portainer_environment_id?: string | null;
            /** Portainer Stack Name */
            portainer_stack_name?: string | null;
            /** Container Selectors */
            container_selectors?: {
                [key: string]: unknown;
            };
            /** Health Config */
            health_config?: {
                [key: string]: unknown;
            };
            /** Grafana Config */
            grafana_config?: {
                [key: string]: unknown;
            };
            /** Loki Config */
            loki_config?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Maintenance
             * @default false
             */
            maintenance: boolean;
            /** Expected Version */
            expected_version?: number | null;
        };
        /**
         * ServiceResponse
         * @description Response DTO for Service; from_attributes lets it serialize the dataclass directly.
         */
        ServiceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Group Name */
            group_name: string;
            /** Environment */
            environment: string;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Service Url */
            service_url?: string | null;
            /** Documentation Url */
            documentation_url?: string | null;
            /** Portainer Environment Id */
            portainer_environment_id?: string | null;
            /** Portainer Stack Name */
            portainer_stack_name?: string | null;
            /** Container Selectors */
            container_selectors: {
                [key: string]: unknown;
            };
            /** Health Config */
            health_config: {
                [key: string]: unknown;
            };
            /** Grafana Config */
            grafana_config: {
                [key: string]: unknown;
            };
            /** Loki Config */
            loki_config: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Maintenance */
            maintenance: boolean;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description One or more dependencies (database, cache) are not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_services_api_v1_services_get: {
        parameters: {
            query?: {
                group_name?: string | null;
                environment?: string | null;
                status?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ServiceResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_api_v1_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_api_v1_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_api_v1_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_service_api_v1_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_status_api_v1_services__service_id__refresh_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_services__service_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    links_api_v1_services__service_id__links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actions_api_v1_services__service_id__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_action_api_v1_services__service_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_action_api_v1_services__service_id__actions__action_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
                action_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_action_api_v1_services__service_id__actions__action_key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
                action_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_api_v1_services__service_id__actions__action_key__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: string;
                action_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_executions_api_v1_executions_get: {
        parameters: {
            query?: {
                service_id?: string | null;
                status?: string | null;
                actor?: string | null;
                source?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExecutionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_api_v1_executions__execution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_executions__execution_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution_api_v1_executions__execution_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_import_api_v1_catalog_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_export_api_v1_catalog_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    audit_events_api_v1_audit_events_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEventResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
